- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: eshop_semestralka
        instance_type: t2.micro
        image:
          id: ami-0b0dcb5067f052a63
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-0016cff4885faa2b6
        security_group: eshop
        exact_count: 2
        network:
          assign_public_ip: yes
        wait: yes
        state: "running"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        aws_session_token: "{{ session_token }}"
      register: ec2
    - name: Add instance host to group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2.instances }}"
    - name: Wait for ssh connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2.instances }}"

- name: Configure ec2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - docker
          - git
        state: latest
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Start docker on startup
      shell: systemctl enable docker
      become: yes
    - name: Set rights to Docker
      shell: usermod -a -G docker ec2-user
      become: yes

    - name: Get project files from Git
      git:
        repo: 'https://github.com/dvorskytomas/4IT572_docker.git'
        dest: ./app
    - name: Build docker image
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes
    - wait_for:
        port:
          80

#- name: Delete old eshop instances
#  hosts: localhost
#  tasks:
#    - name: Limit instances to one
#      amazon.aws.ec2_instance:
#        region: us-east-1
#        filters:
#          "tag:Name": eshop-semestralka
#        exact_count: 1
#        aws_access_key: "{{ access_key }}"
#        aws_secret_key: "{{ secret_key }}"
#        aws_session_token: "{{ session_token }}"
#        instance_type: t2.micro
#        image:
#          id: ami-0b0dcb5067f052a63
#        wait: yes
